/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./components/layouts/actions/Actions.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    Conditions: typeof import('./components/layouts/actions/Conditions.vue')['default']
    Database: typeof import('./components/layouts/actions/Database.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./components/layouts/header/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    Menu: typeof import('./components/layouts/menu/Status.vue')['default']
    MessageBoxDemo: typeof import('./components/MessageBoxDemo.vue')['default']
    Navbar: typeof import('./components/layouts/navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Run: typeof import('./components/layouts/run/Run.vue')['default']
    Status: typeof import('./components/layouts/status/Status.vue')['default']
    Toolbar: typeof import('./components/layouts/toolbar/Toolbar.vue')['default']
    ToolbarData: typeof import('./components/layouts/toolbar/ToolbarData.vue')['default']
    ToolbarLogic: typeof import('./components/layouts/toolbar/ToolbarLogic.vue')['default']
    ToolbarSite: typeof import('./components/layouts/toolbar/ToolbarSite.vue')['default']
    Users: typeof import('./components/layouts/actions/Users.vue')['default']
  }
}
